// Observed-message overlay (Task #36).
//
// The user's directive: "augment the spell database with our own method of verifying
// variations of the cast messages for everything we encounter." This is that method.
//
// ─────────────────────────────────────────────────────────────────────────────
// WHAT IT DOES. As the buffs model folds the log (replay AND live), it feeds every
// player cast (`observeCast`) and every candidate message line (`observeMessage`) here.
// The overlay MINES the association between a message and the spell the player was casting
// when it appeared, keyed by (messageText, spellKey), and counts how often each pairing
// recurs. From those counts it derives a per-message VERDICT:
//
//   VERIFIED          — the message consistently follows exactly ONE spell (n≥2). A
//                       reliable identifier: seeing it proves that spell landed.
//   SHARED / GENERIC  — the message follows MULTIPLE spells (e.g. "You feel different."
//                       for every illusion, "You feel much faster." for four hastes). It
//                       can NOT name a spell on its own — resolution needs cast history.
//   CONTRADICTS-WIKI  — the observed pairing differs from spells.json's msg_* for that
//                       spell (the wiki is known-wrong in places — e.g. Symbol of Pinzarn,
//                       whose real landing route is a heal line, not its listed message).
//   UNKNOWN           — too few observations to judge (a single spell, n<2).
//
// ─────────────────────────────────────────────────────────────────────────────
// THE EFFECTIVE DB. `deriveCorrections()` turns the learned registry into a small set of
// corrections layered OVER spells.json (overlay WINS): a VERIFIED single-spell landing
// message the DB was missing becomes a learned msg_cast_on_you the parser/module can trust;
// a CONTRADICTS-WIKI message surfaces the disagreement. A future agent should consult the
// overlay before trusting a wiki message — a SHARED verdict means "don't trust this message
// to name a spell."
//
// ─────────────────────────────────────────────────────────────────────────────
// PERSISTENCE. The buffs module owns an instance; the overlay is serialized to userData
// (versioned JSON, debounced) so it accretes across sessions, and a committed BASELINE
// snapshot (src/main/data/messageOverlay.baseline.json, generated by
// scripts/gen-message-overlay.ts from the full log) ships so fresh installs benefit from
// day one. On startup the baseline is loaded, then the persisted user overlay is merged on
// top (user observations add to the baseline counts).

import type {
  MessageOverlay,
  OverlayMessage,
  OverlayVerdict,
  SpellEntry
} from '../../shared/types'
import { S, type FoldSchema } from '../foldCache/schema'
import { castOnOtherSuffix } from './spellDb'

/** Overlay schema version — bump to invalidate a stale on-disk snapshot. */
export const OVERLAY_VERSION = 1

/** How long after a cast a message line is attributed to it (ms). Mirrors the landing window. */
const ASSOCIATION_WINDOW_MS = 6_000

/** Minimum observations before a message earns a non-UNKNOWN verdict. */
const MIN_OBSERVATIONS = 2

/** A pending cast the overlay may still associate messages with. */
interface RecentCast {
  spellKey: string
  spellDisplay: string
  ts: number
}

/** Accumulated per-(message) association counts. */
interface MessageRecord {
  text: string
  role: 'landing' | 'wearsOff'
  /** spellKey → { display, count } */
  bySpell: Map<string, { display: string; count: number }>
}

/** Canonical spell key: lowercase, trimmed, trailing Roman rank stripped (mirrors parser). */
const RANK_TAIL_RE = / (?:i|ii|iii|iv|v|vi|vii|viii|ix|x)$/i
function canonKey(name: string): string {
  return name.trim().replace(RANK_TAIL_RE, '').trim().toLowerCase()
}

/**
 * True when a log line is the cast-on-OTHER form of a wiki message — it ENDS WITH the
 * invariant suffix (the wiki's "Someone <suffix>", the log naming the real target). Mirrors
 * parser.matchCastOnOther's tail test so we don't misflag a named-target landing line as a
 * self-message contradiction.
 */
function messageMatchesOtherSuffix(text: string, suffix: string): boolean {
  const attach = suffix.startsWith("'s") ? '' : ' '
  const tail = attach + suffix
  return text.endsWith(tail) && text.length > tail.length
}

/** A derived verdict for one message, plus the wiki disagreement when there is one. */
interface VerdictResult {
  verdict: OverlayVerdict
  wikiConflict?: { spell: string; wikiText: string }
}

/**
 * The LANDING half of verdictFor: the message was unambiguously anchored to the single spell
 * `spellDisplay`, and the DB knows that spell. Split out of verdictFor only to keep each
 * function's branch count in range — the tests below run in the exact same order as before.
 *
 * A landing line can be the SELF form (msg_cast_on_you) OR the on-OTHER form (the
 * wiki's "Someone <suffix>" → the log names the target, so we match by suffix). If
 * the observed line matches EITHER wiki form for this spell, it is CONSISTENT with
 * the wiki — not a contradiction. Only a line matching NEITHER (while the spell was
 * unambiguously the anchor) is a genuine wiki inaccuracy (e.g. Symbol of Pinzarn).
 */
function landingVerdict(rec: MessageRecord, spellDisplay: string, dbSpell: SpellEntry): VerdictResult {
  const you = dbSpell.msgCastOnYou
  if (you && you === rec.text) return { verdict: 'verified' }
  const otherSuffix = dbSpell.msgCastOnOther ? castOnOtherSuffix(dbSpell.msgCastOnOther) : null
  if (otherSuffix && messageMatchesOtherSuffix(rec.text, otherSuffix)) {
    return { verdict: 'verified' }
  }
  // The DB has a self message for this spell but we observed a DIFFERENT self-shaped
  // line → contradiction. If the DB has NO self message at all, treat it as a newly
  // VERIFIED landing message (a variation the wiki simply omits), not a contradiction.
  if (you) return { verdict: 'contradicts-wiki', wikiConflict: { spell: spellDisplay, wikiText: you } }
  return { verdict: 'verified' }
}

/**
 * The mining accumulator + verdict derivation. Deliberately dependency-free and pure over
 * its inputs so it can run identically in a replay-only generator script and in the live
 * module. `spellsByKey` (from the DB) is used ONLY to detect wiki contradictions.
 */
export class MessageOverlayMiner {
  /** messageText → record. */
  private records = new Map<string, MessageRecord>()
  /** The most-recent cast(s) still inside the association window (newest last). */
  private recentCasts: RecentCast[] = []
  /**
   * THE NEWEST LOG INSTANT THIS MINER HAS OBSERVED, and the overlay's `updatedAt` (JOS-208
   * phase 2). It used to be `new Date().toISOString()` — a WALL-CLOCK read inside a published
   * fold snapshot, which the differential harness caught the moment the buffs module joined the
   * matrix: two arms folding the identical bytes built their overlay milliseconds apart and
   * disagreed on every split point of every fixture, for a field that describes nothing about the
   * two folds being compared.
   *
   * It is now what it should always have been: the LOG's own clock. "Current as of this instant
   * in the log" is a statement about the observations the overlay is made of; "current as of when
   * this object happened to be built" is a statement about the reader. Zero before the first
   * observation — a merged baseline does NOT move it, because a merge carries counts and no
   * instants, and inventing one from the file it came from would be a wall clock with a longer
   * paper trail.
   */
  private lastObservedTs = 0
  /** DB spells keyed by canonical name (for contradiction detection); optional. */
  private readonly spellsByKey?: Map<string, SpellEntry>

  constructor(spellsByKey?: Map<string, SpellEntry>) {
    this.spellsByKey = spellsByKey
  }

  /** Record that the player began casting a spell (the association anchor). */
  observeCast(spellDisplay: string, ts: number): void {
    this.expire(ts)
    if (ts > this.lastObservedTs) this.lastObservedTs = ts
    this.recentCasts.push({ spellKey: canonKey(spellDisplay), spellDisplay, ts })
  }

  /**
   * Record a candidate message line and associate it with the recent cast — but ONLY when
   * the anchor is UNAMBIGUOUS: exactly one distinct spell was cast in the window. During a
   * Quick Buff burst or heavy combat, several casts share the window and we can't honestly
   * attribute a message to any one of them, so we SKIP (a coincidental pairing would poison
   * the verdict). This unambiguous-anchor rule is what keeps VERIFIED verdicts trustworthy —
   * a message that consistently follows a single-cast window really is that spell's message.
   * `role` distinguishes a landing message from a wears-off message.
   */
  observeMessage(text: string, ts: number, role: 'landing' | 'wearsOff'): void {
    this.expire(ts)
    if (ts > this.lastObservedTs) this.lastObservedTs = ts
    if (this.recentCasts.length === 0) return
    // Unambiguous anchor: all recent casts must be the SAME spell (a recast counts as one).
    const distinct = new Set(this.recentCasts.map((c) => c.spellKey))
    if (distinct.size !== 1) return
    const cast = this.recentCasts[this.recentCasts.length - 1]
    let rec = this.records.get(text)
    if (!rec) {
      rec = { text, role, bySpell: new Map() }
      this.records.set(text, rec)
    }
    const s = rec.bySpell.get(cast.spellKey)
    if (s) s.count++
    else rec.bySpell.set(cast.spellKey, { display: cast.spellDisplay, count: 1 })
  }

  /** Drop casts that have aged out of the association window. */
  private expire(now: number): void {
    if (this.recentCasts.length === 0) return
    this.recentCasts = this.recentCasts.filter((c) => now - c.ts <= ASSOCIATION_WINDOW_MS)
  }

  /** Merge a persisted/baseline overlay's counts INTO this miner (additive). */
  merge(overlay: MessageOverlay | null | undefined): void {
    if (!overlay) return
    for (const m of overlay.messages) {
      let rec = this.records.get(m.text)
      if (!rec) {
        rec = { text: m.text, role: m.role, bySpell: new Map() }
        this.records.set(m.text, rec)
      }
      for (const sp of m.spells) {
        const key = canonKey(sp.spell)
        const cur = rec.bySpell.get(key)
        if (cur) cur.count += sp.count
        else rec.bySpell.set(key, { display: sp.spell, count: sp.count })
      }
    }
  }

  /** Derive a message's verdict from its per-spell counts + the DB (for contradictions). */
  private verdictFor(rec: MessageRecord): VerdictResult {
    const spells = [...rec.bySpell.values()]
    const total = spells.reduce((a, s) => a + s.count, 0)
    const distinct = spells.length
    if (distinct >= 2) return { verdict: 'shared' }
    if (total < MIN_OBSERVATIONS) return { verdict: 'unknown' }
    // Exactly one spell, seen ≥2×: VERIFIED — unless it contradicts the wiki's msg_* for
    // that spell (the DB says this spell prints a DIFFERENT message for this role).
    const only = spells[0]
    const dbSpell = this.spellsByKey?.get(canonKey(only.display))
    if (dbSpell) {
      if (rec.role === 'landing') return landingVerdict(rec, only.display, dbSpell)
      // wears-off role.
      const wikiText = dbSpell.msgWearsOff
      if (wikiText && wikiText !== rec.text) {
        return { verdict: 'contradicts-wiki', wikiConflict: { spell: only.display, wikiText } }
      }
    }
    return { verdict: 'verified' }
  }

  /** Build the served/persisted overlay from the current accumulator. */
  build(): MessageOverlay {
    const messages: OverlayMessage[] = []
    const stats = { verified: 0, shared: 0, contradictions: 0, unknown: 0 }
    for (const rec of this.records.values()) {
      const spells = [...rec.bySpell.values()]
        .map((s) => ({ spell: s.display, count: s.count }))
        .sort((a, b) => b.count - a.count || a.spell.localeCompare(b.spell))
      const total = spells.reduce((a, s) => a + s.count, 0)
      const { verdict, wikiConflict } = this.verdictFor(rec)
      messages.push({ text: rec.text, role: rec.role, verdict, spells, total, wikiConflict })
      if (verdict === 'verified') stats.verified++
      else if (verdict === 'shared') stats.shared++
      else if (verdict === 'contradicts-wiki') stats.contradictions++
      else stats.unknown++
    }
    // Densest / most-informative first: contradictions, then verified, then shared, then
    // unknown; within a class by total observations desc.
    const rank: Record<OverlayVerdict, number> = {
      'contradicts-wiki': 0,
      verified: 1,
      shared: 2,
      unknown: 3
    }
    messages.sort((a, b) => rank[a.verdict] - rank[b.verdict] || b.total - a.total || a.text.localeCompare(b.text))
    return {
      version: OVERLAY_VERSION,
      // THE LOG'S CLOCK, NOT THE MACHINE'S — see `lastObservedTs` for the divergence that moved it.
      updatedAt: new Date(this.lastObservedTs).toISOString(),
      messages,
      stats
    }
  }

  /**
   * Derive the EFFECTIVE-DB corrections (overlay wins over spells.json). Returns a map of
   * messageText → the single spell it VERIFIABLY identifies, for landing messages the DB
   * either omits or gets wrong. A SHARED message yields no correction (it can't name a
   * spell). A CONTRADICTS-WIKI message yields a correction pointing at the OBSERVED spell.
   *
   * We ONLY emit a correction for a SELF-shaped message — one that does NOT end with any
   * spell's cast-on-other SUFFIX (those name a mob target, not the player, so registering
   * them as msg_cast_on_you would wrongly fire a self buffApply for a debuff-on-a-mob line).
   * The self test uses the DB's own cast-on-other suffixes, so it needs the DB (a miner
   * built without one emits no corrections — correct: nothing to correct against).
   */
  deriveLandingCorrections(): Map<string, { spell: string; contradicts?: string }> {
    const out = new Map<string, { spell: string; contradicts?: string }>()
    const built = this.build()
    for (const m of built.messages) {
      if (m.role !== 'landing') continue
      if (this.looksCastOnOther(m.text)) continue
      if (m.verdict === 'verified') {
        out.set(m.text, { spell: m.spells[0].spell })
      } else if (m.verdict === 'contradicts-wiki' && m.wikiConflict) {
        out.set(m.text, { spell: m.spells[0].spell, contradicts: m.wikiConflict.spell })
      }
    }
    return out
  }

  // ---- the checkpoint seam (JOS-208 phase 2) --------------------------------------------------
  //
  // THE SECOND NAMED DEBT, PAID. attach.ts listed this miner as outside the container, and it is
  // fold state twice over: the `buffs` snapshot PUBLISHES what it builds (`BuffsSnap.overlay`),
  // and the registry it accretes is what a cold replay of the same bytes rebuilds line by line.
  //
  // WHAT TRAVELS IS THE WHOLE ACCUMULATOR, seeded counts included, and that needs saying because
  // the seed is store-derived. `merge()` folds the committed baseline and the user's persisted
  // overlay INTO the same per-message counts the log's own observations land in, and the two are
  // not separable afterwards — by construction, since a merge is an addition. The one-truth rule
  // is not broken by that: the composition root seeds a FRESH miner from the same two sources on
  // every launch, and a restore then replaces the whole object, so the restored counts are
  // (baseline + user overlay + everything the log taught up to B) — exactly what the cold arm
  // holds at B. What must never happen is a restore that lands ON TOP of a seeded miner, which
  // would double the baseline; `deserializeFold` REPLACES rather than merges, which is the
  // difference.
  //
  // `spellsByKey` is not stored: it is the effective DB, rebuilt before any module exists.

  static readonly FOLD_SCHEMA: FoldSchema = S.obj({
    records: S.arr(
      S.tuple(
        S.str,
        S.obj({
          text: S.str,
          role: S.enum('landing', 'wearsOff'),
          bySpell: S.arr(S.tuple(S.str, S.obj({ display: S.str, count: S.num })))
        })
      )
    ),
    recentCasts: S.arr(S.obj({ spellKey: S.str, spellDisplay: S.str, ts: S.num })),
    lastObservedTs: S.num
  })

  serializeFold(): OverlayMinerFoldState {
    const records: OverlayMinerFoldState['records'] = []
    for (const [text, rec] of this.records) {
      records.push([text, { text: rec.text, role: rec.role, bySpell: [...rec.bySpell].map(([k, v]) => [k, { ...v }]) }])
    }
    return {
      records,
      recentCasts: this.recentCasts.map((c) => ({ ...c })),
      lastObservedTs: this.lastObservedTs
    }
  }

  /** REPLACE the accumulator (never merge — see the seam's note). Validated by `BuffsModule`. */
  deserializeFold(state: OverlayMinerFoldState): void {
    this.records = new Map(
      state.records.map(([text, rec]) => [text, { text: rec.text, role: rec.role, bySpell: new Map(rec.bySpell) }])
    )
    this.recentCasts = state.recentCasts
    this.lastObservedTs = state.lastObservedTs
  }

  /** True when a line ends with ANY DB cast-on-other suffix (⇒ it names a mob, not self). */
  private looksCastOnOther(text: string): boolean {
    if (!this.spellsByKey) return false
    for (const s of this.spellsByKey.values()) {
      if (!s.msgCastOnOther) continue
      const suf = castOnOtherSuffix(s.msgCastOnOther)
      if (suf && messageMatchesOtherSuffix(text, suf)) return true
    }
    return false
  }
}

/** The miner's accumulator as plain data — the effective DB deliberately absent. */
export interface OverlayMinerFoldState {
  records: [string, { text: string; role: 'landing' | 'wearsOff'; bySpell: [string, { display: string; count: number }][] }][]
  recentCasts: RecentCast[]
  lastObservedTs: number
}
